detection/initial_access/unexpected-webmail-downloads.sql
This better reflects what we're commonly seeing.
=> webmail: Add .jfif exception, remove exceptions for .bz2, .gz, .tar, .zstd

detection/privesc/setxid-cmdline-overflow-attempt.sql
Detects setuid binaries that have recently been passed large command-lines.
=> Add setxid-cmdline-overflow-attempt.sql

detection/execution/unexpected-sysctl-calls.sql
Often called by Malware to determine if they are running within a VM.
=> new detector: unexpected sysctl calls

detection/credentials/macos_keyboard_sniffer.sql, detection/credentials/unexpected-dev-opener-macos.sql, detection/discovery/unexpected-netutil-calls-macos.sql, detection/discovery/unexpected-pcap-user-macos.sql, detection/evasion/parent-missing-from-disk-macos.sql, detection/execution/exotic-command-events-macos.sql, detection/execution/exotic-commands-macos.sql, detection/execution/recently-created-executables-macos.sql, detection/execution/unexpected-execdir-events-macos.sql, detection/execution/unexpected-root-signer-macos.sql, detection/execution/unexpected-security-framework-program-macos.sql, detection/execution/unexpected-sysutils-macos.sql, detection/execution/unexpected-xattr-calls-macos.sql, detection/privesc/unexpected-elevated-children-events_macos.sql, detection/privesc/unexpected-privilege-escalation_macos.sql, fragments/process_event_parents_macos.sql
As far as I am aware, cgroups are a linux only [feature](https://en.wikipedia.org/wiki/Cgroups)
Checking with the osquery schema for the `processes` [table](https://github.com/osquery/osquery/blob/master/specs/processes.table) , we can see that the `cgroup_path` field is billed as a Linux only field:
```
extended_schema(LINUX, [
Column("cgroup_path", TEXT, "The full hierarchical path of the process's control group")
```
Testing this on my local machine through the `osqueryi` shell, and also as part of the schedule with `osqueryd` has produced errors with execution as the `cgroup_path` field is not recognised on macOS.
As a result I tried to remove all the references to `cgroup_path`, as from my understanding of the queries that used them, they are mostly used as enrichment fields.
=> Modified detections explicitly targeted towards macOS to not include cgroup field

fragments/README.md, fragments/process_parents_macos.sql
Fixes the last errant cgroup inclusion, and fixes #161
=> Remove cgroup from macOS reference fragment, add fragments README

detection/evasion/overwritten-memory-map-ddexec-linux.sql
Detects the use of https://github.com/arget13/DDexec
=> New detector: overwritten memory map

detection/evasion/overwritten-memory-map-ddexec-linux.sql
=> overwritten memory: filter out pathless kernel bits

detection/credentials/macos_keyboard_sniffer.sql
Related to #185 
I'm temporarily backing this change out until there is more evidence as to why osquery might be sniffing for keystrokes. 
Also run `make reformat-updates` and `sort -u` on exceptions.
=> macos sniffers: back out osquery change until we understand it better

detection/execution/exotic-command-events-macos.sql, detection/execution/exotic-commands-macos.sql, detection/execution/unexpected-chmod-exec-event-linux.sql, detection/execution/unexpected-chmod-exec-event-macos.sql
They use subtly different fields to assess a truly functional execve() call.
=> unexpected-chmod-exec: Split and Linux/macOS queries

detection/persistence/minimal-socket-client-macos.sql
Creating an exception for the [Macdown application](https://macdown.uranusjr.com/). Let me know if this isn't the correct spot for an exception
=> Add Macdown as an exception to minimal-socket-client-macos

detection/evasion/unusually-tainted-kernel-linux.sql
If folks go to the trouble of signing their out-of-tree drivers, it's probably not a random rootkit. This was seen with v4l2loopback.ko
/cc @xnox
=> Ignore taint code 4096 (out-of-tree driver)

detection/initial_access/yara-recently-downloaded-packed.sql
This runs the queries from https://github.com/chainguard-dev/bincapz/tree/main/rules/evasion/packer against files modified in the last 12 hours across a variety of directories.
=> new detection: recently downloaded files which have been packed

detection/persistence/suspicious-systemd-unit.sql
Based largely on https://github.com/chainguard-dev/bincapz/tree/main/rules/systemd - this finds systemd units that were likely installed by malware.
references:
* https://attack.mitre.org/techniques/T1543/002/ (Create or Modify System Process: Systemd Service)
* https://www.cadosecurity.com/blog/spinning-yarn-a-new-linux-malware-campaign-targets-docker-apache-hadoop-redis-and-confluence
* https://sandflysecurity.com/blog/log4j-kinsing-linux-malware-in-the-wild/
=> new detection: suspicious systemd units

detection/c2/unexpected-dns-traffic-events.sql, detection/c2/unexpected-https-linux.sql, detection/evasion/hidden-executable.sql, detection/evasion/unexpected-process-extension-linux.sql, detection/evasion/unusual-executable-name-linux.sql, detection/execution/recently-created-executables-long-lived-linux.sql, detection/execution/recently-created-executables-long-lived-macos.sql, detection/execution/tiny-executable-events.sql, detection/exfil/high_disk_bytes_read.sql, detection/initial_access/unexpected-shell-parents.sql, detection/persistence/suspicious-systemd-unit.sql, detection/persistence/unexpected-active-systemd-units.sql
- https-linux: mark it as "extra" so we don't deploy it by default
- DNS: Add wolfi.dev and any terraform provider to the exceptions list
- Hidden executable: add Linuxbrew. We should probably also add `$HOME/.%` in a future PR.
- high disk bytes read: add bin directories to the exceptions list
- systemd: add exceptions for bluefin services, mark unexpected query as extra
=> mark https-linux extra, minor query tuning

Makefile
It fixes the newline munging problem we'd been seeing with `suspicious-systemd-unit`.
=> upgrade osqtool dependency to v1.4.2

detection/c2/unexpected-dns-traffic.sql, detection/credentials/unexpected-dev-opener-linux.sql, detection/evasion/hidden-cwd.sql, detection/evasion/hidden-executable.sql, detection/evasion/parent-missing-from-disk-linux.sql, detection/evasion/unusual-executable-name-macos.sql, detection/execution/sketchy-fetcher-events.sql, detection/execution/tiny-executable-events.sql
This changes `parent-missing-from-disk-linux.sql` to have a more generalized class of exceptions based on directories, to avoid whack-a-mole from system upgrades.
=> fpr: bpftool, curl, pulumi, Docker Desktop, go tests

detection/c2/unexpected-https-macos.sql, detection/credentials/unexpected-dev-opener-linux.sql, detection/evasion/hidden-executable.sql, detection/evasion/unexpected-dev-entries.sql, detection/persistence/unexpected-device-linux.sql, detection/persistence/unexpected-listening-port-macos.sql
This PR adds additional exceptions for the Arc browser, busybox, Edge, and Envoy and fixes two exceptions from #413.
=> Add exceptions for Arc, busybox, and Edge; fix existing exceptions

detection/c2/unexpected-https-macos.sql, detection/collection/high-disk-bytes-written.sql, detection/evasion/hidden-executable.sql, detection/evasion/unexpected-dev-entries.sql, detection/evasion/unexpected-process-extension-linux.sql, detection/execution/recently-created-executables-long-lived-macos.sql, detection/execution/unexpected-long-running-security-framework-macos.sql
- unexpected-https-macos: add extra tag
- high-disk-bytes-written: add extra tag
- hidden executable: add more generic patterns to decrease whack-a-mole
- unexpected dev entries: fix edge bug
- long running framework: add nix exception
- recently created, long running: refactor
=> Address noisy alerts (https-macos, hidden exec, bytes written, dev entries, long running)

detection/persistence/unexpected-launchd-program-arguments.sql
I recently added Zoom to my machine, and this alert fired. We've seen it a couple times elsewhere as well.
Add the Zoom program authority to the list.
```bash
codesign -d -vvv /Applications/zoom.us.app
Executable=/Applications/zoom.us.app/Contents/MacOS/zoom.us
Identifier=us.zoom.xos
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20500 size=919 flags=0x10000(runtime) hashes=18+7 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=345752c25f118b0f729c16a43b88008702d5b636
CandidateCDHashFull sha256=345752c25f118b0f729c16a43b88008702d5b6363dce1b6f188d183df65ba74c
Hash choices=sha256
CMSDigest=345752c25f118b0f729c16a43b88008702d5b6363dce1b6f188d183df65ba74c
CMSDigestType=2
CDHash=345752c25f118b0f729c16a43b88008702d5b636
Signature size=9032
**Authority=Developer ID …
```
=> Add Zoom to the launchd list

detection/persistence/shady-chrome-extension-author.sql, detection/persistence/unexpected-chrome-extensions.sql
Based on the list from the bottom of this recent Ars article: https://arstechnica.com/security/2025/01/googles-chrome-web-store-has-a-serious-spam-problem-promoting-shady-extensions/
=> Add newly-documented Chrome Extension authors

detection/evasion/unexpected-alf-exceptions-macos.sql
This removes the too-specific line. I removed it because it also appeared to be redundant due to:
https://github.com/chainguard-dev/osquery-defense-kit/blob/19dab18675c59a5840b9fc195df3cb105d5e3367/detection/evasion/unexpected-alf-exceptions-macos.sql#L121-L123
=> Remove redundant line
